services:
  laravel:
    build:
      context: ./docker/laravel
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: laravel_app
    restart: always
    depends_on:
      - mysql
      - mailhog
    networks:
      - american-trip
    ports:
      - "80:80"
      - "5173:5173" # Vite (opcional)
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: docker
      DB_USERNAME: docker
      DB_PASSWORD: docker
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: admin@example.com
      MAIL_FROM_NAME: "Laravel App"

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    networks:
      - american-trip
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    mem_limit: 500mb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - american-trip
    ports:
      - "8080:80"

  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    restart: always
    networks:
      - american-trip
    ports:
      - "8025:8025"

networks:
  american-trip:
    driver: bridge
